/**
 * a multiple choice quiz about thermochemistry and spontaneity 
 * 
 * modified 20210810
 * date 20210810
 *
 * @filename FrmMCQuiz.java
 * @author Emily Su
 * @version 1.0
 */
// note: "MC" stands for "multiple choice"
// note: "Q" stands for "question"
// note: "Ans" stands for "answer"
public class FrmMCQuiz extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L; // https://stackoverflow.com/questions/2288937/what-does-it-mean-the-serializable-class-does-not-declare-a-static-final-serial

    int numQsCompleted;
    int numQsCorrect;
    int numQsIncorrect;
    double percentageCorrect;
    double percentageCorrectRounded;
    final int NUMBER_OF_QUESTIONS = 5;

    /**
     * Creates new form FrmMCQuiz
     */
    public FrmMCQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblOverallStatsInst2 = new javax.swing.JLabel();
        btnRetry = new javax.swing.JButton();
        lblRetryInst2 = new javax.swing.JLabel();
        lblRetryInst1 = new javax.swing.JLabel();
        lblOverallStatsInst1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblInst1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblQ2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        txtUserAns1 = new javax.swing.JTextField();
        txtUserAns2 = new javax.swing.JTextField();
        txtUserAns3 = new javax.swing.JTextField();
        lblUserAns1 = new javax.swing.JLabel();
        lblUserAns2 = new javax.swing.JLabel();
        lblUserAns3 = new javax.swing.JLabel();
        btnEnter1 = new javax.swing.JButton();
        btnEnter2 = new javax.swing.JButton();
        btnEnter3 = new javax.swing.JButton();
        lblA1 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblB2 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();
        lblB3 = new javax.swing.JLabel();
        lblC3 = new javax.swing.JLabel();
        lblQ1 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();
        lblStatus3 = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        lblResultStatus1 = new javax.swing.JLabel();
        lblResultStatus2 = new javax.swing.JLabel();
        lblResultStatus3 = new javax.swing.JLabel();
        lblC1 = new javax.swing.JLabel();
        lblB1 = new javax.swing.JLabel();
        lblE1 = new javax.swing.JLabel();
        lblE2 = new javax.swing.JLabel();
        lblD3 = new javax.swing.JLabel();
        lblE3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblQ5 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        txtUserAns4 = new javax.swing.JTextField();
        txtUserAns5 = new javax.swing.JTextField();
        lblUserAns4 = new javax.swing.JLabel();
        lblUserAns5 = new javax.swing.JLabel();
        btnEnter5 = new javax.swing.JButton();
        lblD5 = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        lblC5 = new javax.swing.JLabel();
        lblC4 = new javax.swing.JLabel();
        lblA5 = new javax.swing.JLabel();
        lblB5 = new javax.swing.JLabel();
        lblStatus4 = new javax.swing.JLabel();
        lblResultStatus5 = new javax.swing.JLabel();
        lblResultStatus4 = new javax.swing.JLabel();
        lblE4 = new javax.swing.JLabel();
        lblB4 = new javax.swing.JLabel();
        lblD4 = new javax.swing.JLabel();
        lblStatus5 = new javax.swing.JLabel();
        lblE5 = new javax.swing.JLabel();
        btnEnter4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblOverallStats = new javax.swing.JLabel();
        lblPercentage = new javax.swing.JLabel();
        lblPercentSign = new javax.swing.JLabel();
        lblQsIncorrect = new javax.swing.JLabel();
        lblQsCorrect = new javax.swing.JLabel();
        lblValueQsCorrect = new javax.swing.JLabel();
        lblValueQsIncorrect = new javax.swing.JLabel();
        lblValuePercentage = new javax.swing.JLabel();
        lblInst2 = new javax.swing.JLabel();
        lblInstProgress = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblValueProgress = new javax.swing.JLabel();
        btnOverallStats = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1226, 634));
        setMinimumSize(new java.awt.Dimension(1226, 634));
        setSize(new java.awt.Dimension(1226, 634));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1221, 634));
        jPanel1.setMinimumSize(new java.awt.Dimension(1221, 634));
        jPanel1.setPreferredSize(new java.awt.Dimension(1221, 634));

        lblOverallStatsInst2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 14)); // NOI18N
        lblOverallStatsInst2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOverallStatsInst2.setText("based on all 5 of the given questions");

        btnRetry.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 20)); // NOI18N
        btnRetry.setForeground(new java.awt.Color(102, 51, 255));
        btnRetry.setText("Retry the entire quiz");
        btnRetry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetry.setMaximumSize(new java.awt.Dimension(242, 35));
        btnRetry.setMinimumSize(new java.awt.Dimension(242, 35));
        btnRetry.setPreferredSize(new java.awt.Dimension(242, 35));
        btnRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetryActionPerformed(evt);
            }
        });

        lblRetryInst2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 14)); // NOI18N
        lblRetryInst2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetryInst2.setText(" and check your statistics again!");

        lblRetryInst1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 14)); // NOI18N
        lblRetryInst1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetryInst1.setText("You will be able to enter new answers");

        lblOverallStatsInst1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 14)); // NOI18N
        lblOverallStatsInst1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOverallStatsInst1.setText("Your overall statistics will be calculated");

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));

        lblHeader.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 36)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Thermochemistry and Spontaneity Multiple Choice Quiz");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        lblInst1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 12)); // NOI18N
        lblInst1.setText("Please enter your answer A, B, C, D, or E in the text field for each question and press the respective Enter button. ");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        lblQ2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblQ2.setText("2) What does H represent?");

        lblQ3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblQ3.setText("3) What does S represent?");

        txtUserAns1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        txtUserAns1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserAns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserAns1ActionPerformed(evt);
            }
        });

        txtUserAns2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        txtUserAns2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserAns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserAns2ActionPerformed(evt);
            }
        });

        txtUserAns3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        txtUserAns3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserAns3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserAns3ActionPerformed(evt);
            }
        });

        lblUserAns1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblUserAns1.setText("Your Answer:");

        lblUserAns2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblUserAns2.setText("Your Answer:");

        lblUserAns3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblUserAns3.setText("Your Answer:");

        btnEnter1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        btnEnter1.setForeground(new java.awt.Color(102, 51, 255));
        btnEnter1.setText("Enter");
        btnEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnter1ActionPerformed(evt);
            }
        });

        btnEnter2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        btnEnter2.setForeground(new java.awt.Color(102, 51, 255));
        btnEnter2.setText("Enter");
        btnEnter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnter2ActionPerformed(evt);
            }
        });

        btnEnter3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        btnEnter3.setForeground(new java.awt.Color(102, 51, 255));
        btnEnter3.setText("Enter");
        btnEnter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnter3ActionPerformed(evt);
            }
        });

        lblA1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblA1.setText("A. mass");

        lblD2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblD2.setText("D. melting point");

        lblA2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblA2.setText("A. enthalpy");

        lblB2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblB2.setText("B. temperature");

        lblC2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblC2.setText("C. volume");

        lblA3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblA3.setText("A. entropy");

        lblB3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblB3.setText("B. Superman");

        lblC3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblC3.setText("C. enthalpy");

        lblQ1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblQ1.setText("1) Which one is an instrinsic property?");

        lblStatus1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblStatus1.setText("Answer Status:");

        lblStatus2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblStatus2.setText("Answer Status:");

        lblStatus3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblStatus3.setText("Answer Status:");

        lblD1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblD1.setText("D. endothermic");

        lblResultStatus1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblResultStatus1.setText("You have not answered. ");

        lblResultStatus2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblResultStatus2.setText("You have not answered. ");

        lblResultStatus3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblResultStatus3.setText("You have not answered. ");

        lblC1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblC1.setText("C. exothermic");

        lblB1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblB1.setText("B. boiling point");

        lblE1.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblE1.setText("E. enthalpy");

        lblE2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblE2.setText("E. entropy");

        lblD3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblD3.setText("D. temperature");

        lblE3.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblE3.setText("E. heat");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblQ1)
                        .addGap(82, 82, 82)
                        .addComponent(lblUserAns1)
                        .addGap(9, 9, 9)
                        .addComponent(txtUserAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblB1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC1)
                            .addComponent(lblD1))
                        .addGap(27, 27, 27)
                        .addComponent(lblE1)
                        .addGap(114, 114, 114)
                        .addComponent(btnEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblStatus1)
                        .addGap(7, 7, 7)
                        .addComponent(lblResultStatus1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblQ2)
                        .addGap(169, 169, 169)
                        .addComponent(lblUserAns2)
                        .addGap(9, 9, 9)
                        .addComponent(txtUserAns2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA2)
                            .addComponent(lblB2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC2)
                            .addComponent(lblD2))
                        .addGap(21, 21, 21)
                        .addComponent(lblE2)
                        .addGap(122, 122, 122)
                        .addComponent(btnEnter2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblStatus2)
                        .addGap(7, 7, 7)
                        .addComponent(lblResultStatus2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblQ3)
                        .addGap(171, 171, 171)
                        .addComponent(lblUserAns3)
                        .addGap(9, 9, 9)
                        .addComponent(txtUserAns3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA3)
                            .addComponent(lblB3))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC3)
                            .addComponent(lblD3))
                        .addGap(29, 29, 29)
                        .addComponent(lblE3)
                        .addGap(143, 143, 143)
                        .addComponent(btnEnter3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblStatus3)
                        .addGap(7, 7, 7)
                        .addComponent(lblResultStatus3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblA1)
                        .addGap(9, 9, 9)
                        .addComponent(lblB1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblC1)
                        .addGap(9, 9, 9)
                        .addComponent(lblD1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblE1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEnter1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblResultStatus1)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserAns2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserAns2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblA2)
                        .addGap(9, 9, 9)
                        .addComponent(lblB2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblC2)
                        .addGap(9, 9, 9)
                        .addComponent(lblD2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblE2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEnter2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblResultStatus2)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserAns3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserAns3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblA3)
                        .addGap(9, 9, 9)
                        .addComponent(lblB3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblC3)
                        .addGap(9, 9, 9)
                        .addComponent(lblD3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblE3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEnter3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblResultStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        lblQ5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblQ5.setText("5) Which one is a state function?");

        lblQ4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblQ4.setText("4) Which one is a path function?");

        txtUserAns4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        txtUserAns4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserAns4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserAns4ActionPerformed(evt);
            }
        });

        txtUserAns5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        txtUserAns5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserAns5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserAns5ActionPerformed(evt);
            }
        });

        lblUserAns4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblUserAns4.setText("Your Answer:");

        lblUserAns5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblUserAns5.setText("Your Answer:");

        btnEnter5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        btnEnter5.setForeground(new java.awt.Color(102, 51, 255));
        btnEnter5.setText("Enter");
        btnEnter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnter5ActionPerformed(evt);
            }
        });

        lblD5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblD5.setText("D. molecules");

        lblA4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblA4.setText("A. endothermic");

        lblC5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblC5.setText("C. pressure");

        lblC4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblC4.setText("C. melting point");

        lblA5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblA5.setText("A. work");

        lblB5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblB5.setText("B. boiling point");

        lblStatus4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblStatus4.setText("Answer Status:");

        lblResultStatus5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblResultStatus5.setText("You have not answered. ");

        lblResultStatus4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblResultStatus4.setText("You have not answered. ");

        lblE4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblE4.setText("E. heat");

        lblB4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblB4.setText("B. exothermic");

        lblD4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblD4.setText("D. mass");

        lblStatus5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblStatus5.setText("Answer Status:");

        lblE5.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblE5.setText("E. heat");

        btnEnter4.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        btnEnter4.setForeground(new java.awt.Color(102, 51, 255));
        btnEnter4.setText("Enter");
        btnEnter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnter4ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblStatus4)
                        .addGap(7, 7, 7)
                        .addComponent(lblResultStatus4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblQ5)
                        .addGap(125, 125, 125)
                        .addComponent(lblUserAns5)
                        .addGap(9, 9, 9)
                        .addComponent(txtUserAns5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA5)
                            .addComponent(lblB5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC5)
                            .addComponent(lblD5))
                        .addGap(43, 43, 43)
                        .addComponent(lblE5)
                        .addGap(143, 143, 143)
                        .addComponent(btnEnter5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblStatus5)
                        .addGap(7, 7, 7)
                        .addComponent(lblResultStatus5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblQ4)
                        .addGap(127, 127, 127)
                        .addComponent(lblUserAns4)
                        .addGap(9, 9, 9)
                        .addComponent(txtUserAns4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA4)
                            .addComponent(lblB4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC4)
                            .addComponent(lblD4))
                        .addGap(21, 21, 21)
                        .addComponent(lblE4)
                        .addGap(143, 143, 143)
                        .addComponent(btnEnter4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserAns4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserAns4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblA4)
                        .addGap(9, 9, 9)
                        .addComponent(lblB4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblC4)
                        .addGap(9, 9, 9)
                        .addComponent(lblD4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblE4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEnter4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblResultStatus4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserAns5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserAns5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblA5)
                        .addGap(9, 9, 9)
                        .addComponent(lblB5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblC5)
                        .addGap(9, 9, 9)
                        .addComponent(lblD5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblE5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEnter5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblResultStatus5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(569, 186));
        jPanel5.setMinimumSize(new java.awt.Dimension(569, 186));

        lblOverallStats.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblOverallStats.setText("How well did you do on the quiz?");

        lblPercentage.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblPercentage.setText("Percentage:");

        lblPercentSign.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblPercentSign.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPercentSign.setText("%");

        lblQsIncorrect.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblQsIncorrect.setText("Questions Incorrect:");

        lblQsCorrect.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblQsCorrect.setText("Questions Correct:");

        lblValueQsCorrect.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblValueQsCorrect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueQsCorrect.setText("N/A");

        lblValueQsIncorrect.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblValueQsIncorrect.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueQsIncorrect.setText("N/A");

        lblValuePercentage.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 16)); // NOI18N
        lblValuePercentage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValuePercentage.setText("N/A");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblOverallStats))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblQsCorrect)
                        .addGap(14, 14, 14)
                        .addComponent(lblValueQsCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblQsIncorrect)
                        .addGap(3, 3, 3)
                        .addComponent(lblValueQsIncorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblPercentage)
                        .addGap(59, 59, 59)
                        .addComponent(lblValuePercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblPercentSign, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblOverallStats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQsCorrect)
                    .addComponent(lblValueQsCorrect))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQsIncorrect)
                    .addComponent(lblValueQsIncorrect))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPercentage)
                    .addComponent(lblValuePercentage)
                    .addComponent(lblPercentSign)))
        );

        lblInst2.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 12)); // NOI18N
        lblInst2.setText("NOTE: If you have pressed the Enter button for a question, do not press that same button again unless there is an error or you retry the quiz.");

        lblInstProgress.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblInstProgress.setText("Out of 5 questions, you have currently completed:");

        lblValueProgress.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        lblValueProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueProgress.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValueProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblValueProgress))
        );

        btnOverallStats.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 20)); // NOI18N
        btnOverallStats.setForeground(new java.awt.Color(102, 51, 255));
        btnOverallStats.setText("See my overall statistics");
        btnOverallStats.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOverallStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverallStatsActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnOverallStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOverallStatsInst1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOverallStatsInst2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRetry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRetryInst2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblRetryInst1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInst1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInst2))
                        .addGap(18, 18, 18)
                        .addComponent(lblInstProgress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInst1)
                        .addGap(0, 0, 0)
                        .addComponent(lblInst2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInstProgress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOverallStats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOverallStatsInst1)
                                .addGap(0, 0, 0)
                                .addComponent(lblOverallStatsInst2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRetry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRetryInst1)
                                .addGap(0, 0, 0)
                                .addComponent(lblRetryInst2))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOverallStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverallStatsActionPerformed

        // calculation
        percentageCorrect = ((double) numQsCorrect / (double) NUMBER_OF_QUESTIONS) * 100;

        // rounding
        percentageCorrectRounded = Math.round((percentageCorrect) * 10) / 10.0; // https://stackoverflow.com/questions/22186778/using-math-round-to-round-to-one-decimal-place

        // output
        lblValueQsCorrect.setText(String.valueOf(numQsCorrect));
        lblValueQsIncorrect.setText(String.valueOf(numQsIncorrect));
        lblValuePercentage.setText(String.valueOf(percentageCorrectRounded));
    }//GEN-LAST:event_btnOverallStatsActionPerformed

    private void btnRetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetryActionPerformed

        numQsCompleted = 0;
        numQsCorrect = 0;
        numQsIncorrect = 0;
        percentageCorrect = 0;
        percentageCorrectRounded = 0;

        // output
        txtUserAns1.setText("");
        txtUserAns2.setText("");
        txtUserAns3.setText("");
        txtUserAns4.setText("");
        txtUserAns5.setText("");

        lblResultStatus1.setText("You have not answered.");
        lblResultStatus2.setText("You have not answered.");
        lblResultStatus3.setText("You have not answered.");
        lblResultStatus4.setText("You have not answered.");
        lblResultStatus5.setText("You have not answered.");

        lblValueProgress.setText(String.valueOf(numQsCompleted));
        lblValueQsCorrect.setText("N/A");
        lblValueQsIncorrect.setText("N/A");
        lblValuePercentage.setText("N/A");
    }//GEN-LAST:event_btnRetryActionPerformed

    private void btnEnter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnter4ActionPerformed

        String fourthUserAns;
        final String Q4_FIRST_CORRECT_ANS = "E";
        final String Q4_SECOND_CORRECT_ANS = "e";

        // retrieve user information
        fourthUserAns = txtUserAns4.getText();

        // processing and feedback output
        if (fourthUserAns.length() == 1) { // https://stackoverflow.com/questions/49308129/java-verify-user-input-for-one-character
            // score counter
            if ((fourthUserAns.equals(Q4_FIRST_CORRECT_ANS)) || (fourthUserAns.equals(Q4_SECOND_CORRECT_ANS))) {
                lblResultStatus4.setText("Correct!");
                numQsCorrect = numQsCorrect + 1;
            } else {
                lblResultStatus4.setText("Incorrect!");
                numQsIncorrect = numQsIncorrect + 1;
            }
            // progress counter
            numQsCompleted = numQsCompleted + 1;
        } else {
            lblResultStatus4.setText("Error. You must enter an answer that is 1 character. Try again.");
        }

        // progress output
        lblValueProgress.setText(String.valueOf(numQsCompleted));
    }//GEN-LAST:event_btnEnter4ActionPerformed

    private void btnEnter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnter5ActionPerformed

        String fifthUserAns;
        final String Q5_FIRST_CORRECT_ANS = "C";
        final String Q5_SECOND_CORRECT_ANS = "c";

        // retrieve user information
        fifthUserAns = txtUserAns5.getText();

        // processing and feedback output
        if (fifthUserAns.length() == 1) { // https://stackoverflow.com/questions/49308129/java-verify-user-input-for-one-character
            // score counter
            if ((fifthUserAns.equals(Q5_FIRST_CORRECT_ANS)) || (fifthUserAns.equals(Q5_SECOND_CORRECT_ANS))) {
                lblResultStatus5.setText("Correct!");
                numQsCorrect = numQsCorrect + 1;
            } else {
                lblResultStatus5.setText("Incorrect!");
                numQsIncorrect = numQsIncorrect + 1;
            }
            // progress counter
            numQsCompleted = numQsCompleted + 1;
        } else {
            lblResultStatus5.setText("Error. You must enter an answer that is 1 character. Try again.");
        }

        // progress output
        lblValueProgress.setText(String.valueOf(numQsCompleted));
    }//GEN-LAST:event_btnEnter5ActionPerformed

    private void txtUserAns5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserAns5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserAns5ActionPerformed

    private void txtUserAns4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserAns4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserAns4ActionPerformed

    private void btnEnter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnter3ActionPerformed

        String thirdUserAns;
        final String Q3_FIRST_CORRECT_ANS = "A";
        final String Q3_SECOND_CORRECT_ANS = "a";

        // retrieve user information
        thirdUserAns = txtUserAns3.getText();

        // processing and feedback output
        if (thirdUserAns.length() == 1) { // https://stackoverflow.com/questions/49308129/java-verify-user-input-for-one-character
            // score counter
            if ((thirdUserAns.equals(Q3_FIRST_CORRECT_ANS)) || (thirdUserAns.equals(Q3_SECOND_CORRECT_ANS))) {
                lblResultStatus3.setText("Correct!");
                numQsCorrect = numQsCorrect + 1;
            } else {
                lblResultStatus3.setText("Incorrect!");
                numQsIncorrect = numQsIncorrect + 1;
            }
            // progress counter
            numQsCompleted = numQsCompleted + 1;
        } else {
            lblResultStatus3.setText("Error. You must enter an answer that is 1 character. Try again.");
        }

        // progress output
        lblValueProgress.setText(String.valueOf(numQsCompleted));
    }//GEN-LAST:event_btnEnter3ActionPerformed

    private void btnEnter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnter2ActionPerformed

        String secondUserAns;
        final String Q2_FIRST_CORRECT_ANS = "A";
        final String Q2_SECOND_CORRECT_ANS = "a";

        // retrieve user information
        secondUserAns = txtUserAns2.getText();

        // processing and feedback output
        if (secondUserAns.length() == 1) { // https://stackoverflow.com/questions/49308129/java-verify-user-input-for-one-character
            // score counter
            if ((secondUserAns.equals(Q2_FIRST_CORRECT_ANS)) || (secondUserAns.equals(Q2_SECOND_CORRECT_ANS))) {
                lblResultStatus2.setText("Correct!");
                numQsCorrect = numQsCorrect + 1;
            } else {
                lblResultStatus2.setText("Incorrect!");
                numQsIncorrect = numQsIncorrect + 1;
            }
            // progress counter
            numQsCompleted = numQsCompleted + 1;
        } else {
            lblResultStatus2.setText("Error. You must enter an answer that is 1 character. Try again.");
        }

        // progress output
        lblValueProgress.setText(String.valueOf(numQsCompleted));
    }//GEN-LAST:event_btnEnter2ActionPerformed

    private void btnEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnter1ActionPerformed

        String firstUserAns;
        final String Q1_FIRST_CORRECT_ANS = "B";
        final String Q1_SECOND_CORRECT_ANS = "b";

        // retrieve user information
        firstUserAns = txtUserAns1.getText();

        // processing and feedback output
        if (firstUserAns.length() == 1) { // https://stackoverflow.com/questions/49308129/java-verify-user-input-for-one-character
            // score counter
            if ((firstUserAns.equals(Q1_FIRST_CORRECT_ANS)) || (firstUserAns.equals(Q1_SECOND_CORRECT_ANS))) {
                lblResultStatus1.setText("Correct!");
                numQsCorrect = numQsCorrect + 1;
            } else {
                lblResultStatus1.setText("Incorrect!");
                numQsIncorrect = numQsIncorrect + 1;
            }
            // progress counter
            numQsCompleted = numQsCompleted + 1;
        } else {
            lblResultStatus1.setText("Error. You must enter an answer that is 1 character. Try again.");
        }

        // progress output
        lblValueProgress.setText(String.valueOf(numQsCompleted));
    }//GEN-LAST:event_btnEnter1ActionPerformed

    private void txtUserAns3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserAns3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserAns3ActionPerformed

    private void txtUserAns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserAns2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserAns2ActionPerformed

    private void txtUserAns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserAns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserAns1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMCQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMCQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMCQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMCQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMCQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter1;
    private javax.swing.JButton btnEnter2;
    private javax.swing.JButton btnEnter3;
    private javax.swing.JButton btnEnter4;
    private javax.swing.JButton btnEnter5;
    private javax.swing.JButton btnOverallStats;
    private javax.swing.JButton btnRetry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblB4;
    private javax.swing.JLabel lblB5;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblD4;
    private javax.swing.JLabel lblD5;
    private javax.swing.JLabel lblE1;
    private javax.swing.JLabel lblE2;
    private javax.swing.JLabel lblE3;
    private javax.swing.JLabel lblE4;
    private javax.swing.JLabel lblE5;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInst1;
    private javax.swing.JLabel lblInst2;
    private javax.swing.JLabel lblInstProgress;
    private javax.swing.JLabel lblOverallStats;
    private javax.swing.JLabel lblOverallStatsInst1;
    private javax.swing.JLabel lblOverallStatsInst2;
    private javax.swing.JLabel lblPercentSign;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQsCorrect;
    private javax.swing.JLabel lblQsIncorrect;
    private javax.swing.JLabel lblResultStatus1;
    private javax.swing.JLabel lblResultStatus2;
    private javax.swing.JLabel lblResultStatus3;
    private javax.swing.JLabel lblResultStatus4;
    private javax.swing.JLabel lblResultStatus5;
    private javax.swing.JLabel lblRetryInst1;
    private javax.swing.JLabel lblRetryInst2;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel lblStatus3;
    private javax.swing.JLabel lblStatus4;
    private javax.swing.JLabel lblStatus5;
    private javax.swing.JLabel lblUserAns1;
    private javax.swing.JLabel lblUserAns2;
    private javax.swing.JLabel lblUserAns3;
    private javax.swing.JLabel lblUserAns4;
    private javax.swing.JLabel lblUserAns5;
    private javax.swing.JLabel lblValuePercentage;
    private javax.swing.JLabel lblValueProgress;
    private javax.swing.JLabel lblValueQsCorrect;
    private javax.swing.JLabel lblValueQsIncorrect;
    private javax.swing.JTextField txtUserAns1;
    private javax.swing.JTextField txtUserAns2;
    private javax.swing.JTextField txtUserAns3;
    private javax.swing.JTextField txtUserAns4;
    private javax.swing.JTextField txtUserAns5;
    // End of variables declaration//GEN-END:variables
}
