version: "3.1"

services:

  postgres:
    container_name: postgresdb
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  r2dbc-todo-list-application:
    build:
      context: ../todo-list-application
    depends_on:
      - postgres
    image: r2dbc-todo-list-application
    ports:
      - "8080:8080"
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://postgres:5432/todolist
      - spring.liquibase.url=jdbc:postgresql://postgres:5432/todolist

volumes:
  postgres_data:

