use skill_inventory;

INSERT INTO SKILL (skill_name) VALUES ('Full Stack');
INSERT INTO SKILL (skill_name) VALUES ('DevOps');
INSERT INTO SKILL (skill_name) VALUES ('Data');
INSERT INTO SKILL (skill_name) VALUES ('Cloud');
INSERT INTO SKILL (skill_name) VALUES ('Mobile');
INSERT INTO SKILL (skill_name) VALUES ('API');
INSERT INTO SKILL (skill_name) VALUES ('UI');
INSERT INTO SKILL (skill_name) VALUES ('Microservice');
INSERT INTO SKILL (skill_name) VALUES ('Pattern');
INSERT INTO SKILL (skill_name) VALUES ('Design Pattern');
INSERT INTO SKILL (skill_name) VALUES ('Twelve-Factor');
INSERT INTO SKILL (skill_name) VALUES ('Twelve-Factor App');
INSERT INTO SKILL (skill_name) VALUES ('Twelve-Factor methodology');
INSERT INTO SKILL (skill_name) VALUES ('Twelve-Factor App methodology');
INSERT INTO SKILL (skill_name) VALUES ('12 Factor');
INSERT INTO SKILL (skill_name) VALUES ('12 Factor app');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Native');
INSERT INTO SKILL (skill_name) VALUES ('Java');
INSERT INTO SKILL (skill_name) VALUES ('Python');
INSERT INTO SKILL (skill_name) VALUES ('Go');
INSERT INTO SKILL (skill_name) VALUES ('Golang');
INSERT INTO SKILL (skill_name) VALUES ('Kotlin');
INSERT INTO SKILL (skill_name) VALUES ('Javascript');
INSERT INTO SKILL (skill_name) VALUES ('Node.js');
INSERT INTO SKILL (skill_name) VALUES ('C#');
INSERT INTO SKILL (skill_name) VALUES ('Shell Script');
INSERT INTO SKILL (skill_name) VALUES ('TypeScript');
INSERT INTO SKILL (skill_name) VALUES ('Scala');
INSERT INTO SKILL (skill_name) VALUES ('Ruby');
INSERT INTO SKILL (skill_name) VALUES ('Erlang');
INSERT INTO SKILL (skill_name) VALUES ('Object-C');
INSERT INTO SKILL (skill_name) VALUES ('Swift');
INSERT INTO SKILL (skill_name) VALUES ('PHP');
INSERT INTO SKILL (skill_name) VALUES ('Angular');
INSERT INTO SKILL (skill_name) VALUES ('React');
INSERT INTO SKILL (skill_name) VALUES ('VUE');
INSERT INTO SKILL (skill_name) VALUES ('Material');
INSERT INTO SKILL (skill_name) VALUES ('Material UI');
INSERT INTO SKILL (skill_name) VALUES ('Bootstrap');
INSERT INTO SKILL (skill_name) VALUES ('jQuery');
INSERT INTO SKILL (skill_name) VALUES ('Agile');
INSERT INTO SKILL (skill_name) VALUES ('Scrum');
INSERT INTO SKILL (skill_name) VALUES ('SDLC');
INSERT INTO SKILL (skill_name) VALUES ('ITSM');
INSERT INTO SKILL (skill_name) VALUES ('ITIL');
INSERT INTO SKILL (skill_name) VALUES ('Government');
INSERT INTO SKILL (skill_name) VALUES ('Banking');
INSERT INTO SKILL (skill_name) VALUES ('Financial Services');
INSERT INTO SKILL (skill_name) VALUES ('Insurance');
INSERT INTO SKILL (skill_name) VALUES ('Energy');
INSERT INTO SKILL (skill_name) VALUES ('Telecom');
INSERT INTO SKILL (skill_name) VALUES ('Telecommunications');
INSERT INTO SKILL (skill_name) VALUES ('Healthcare');
INSERT INTO SKILL (skill_name) VALUES ('Pharmaceutical');
INSERT INTO SKILL (skill_name) VALUES ('Postal Service');
INSERT INTO SKILL (skill_name) VALUES ('Consulting');
INSERT INTO SKILL (skill_name) VALUES ('IT');
INSERT INTO SKILL (skill_name) VALUES ('Software');
INSERT INTO SKILL (skill_name) VALUES ('Oil & Gas');
INSERT INTO SKILL (skill_name) VALUES ('Petroleum');
INSERT INTO SKILL (skill_name) VALUES ('Retail');
INSERT INTO SKILL (skill_name) VALUES ('Google');
INSERT INTO SKILL (skill_name) VALUES ('Amazon');
INSERT INTO SKILL (skill_name) VALUES ('Microsoft');
INSERT INTO SKILL (skill_name) VALUES ('Salesforce');
INSERT INTO SKILL (skill_name) VALUES ('Oracle');
INSERT INTO SKILL (skill_name) VALUES ('IBM');
INSERT INTO SKILL (skill_name) VALUES ('RedHat');
INSERT INTO SKILL (skill_name) VALUES ('SAP');
INSERT INTO SKILL (skill_name) VALUES ('VMWare');
INSERT INTO SKILL (skill_name) VALUES ('HP');
INSERT INTO SKILL (skill_name) VALUES ('Accenture');
INSERT INTO SKILL (skill_name) VALUES ('Capgemini');
INSERT INTO SKILL (skill_name) VALUES ('Express Scripts');
INSERT INTO SKILL (skill_name) VALUES ('RBC');
INSERT INTO SKILL (skill_name) VALUES ('BMO');
INSERT INTO SKILL (skill_name) VALUES ('NBC');
INSERT INTO SKILL (skill_name) VALUES ('Manulife');
INSERT INTO SKILL (skill_name) VALUES ('Sunlife');
INSERT INTO SKILL (skill_name) VALUES ('CMHC');
INSERT INTO SKILL (skill_name) VALUES ('Canada Post');
INSERT INTO SKILL (skill_name) VALUES ('Hydro One');
INSERT INTO SKILL (skill_name) VALUES ('Husky Energy');
INSERT INTO SKILL (skill_name) VALUES ('Rogers');
INSERT INTO SKILL (skill_name) VALUES ('Telus');
INSERT INTO SKILL (skill_name) VALUES ('Loblaws');
INSERT INTO SKILL (skill_name) VALUES ('OPS');
INSERT INTO SKILL (skill_name) VALUES ('Ontario Public Service');
INSERT INTO SKILL (skill_name) VALUES ('Government of Canada');
INSERT INTO SKILL (skill_name) VALUES ('Federal Government');
INSERT INTO SKILL (skill_name) VALUES ('Ontario Ministry of Children, Community and Social Services');
INSERT INTO SKILL (skill_name) VALUES ('Ontario Ministry of Health and Long-Term Care');
INSERT INTO SKILL (skill_name) VALUES ('Ontario Ministry of Education');
INSERT INTO SKILL (skill_name) VALUES ('CI/CD');
INSERT INTO SKILL (skill_name) VALUES ('pipeline');
INSERT INTO SKILL (skill_name) VALUES ('HTML');
INSERT INTO SKILL (skill_name) VALUES ('HTML 5');
INSERT INTO SKILL (skill_name) VALUES ('CSS');
INSERT INTO SKILL (skill_name) VALUES ('CSS 3');
INSERT INTO SKILL (skill_name) VALUES ('CSS media');
INSERT INTO SKILL (skill_name) VALUES ('Docker');
INSERT INTO SKILL (skill_name) VALUES ('Kubernetes');
INSERT INTO SKILL (skill_name) VALUES ('Container');
INSERT INTO SKILL (skill_name) VALUES ('Containerization orchestration');
INSERT INTO SKILL (skill_name) VALUES ('Terraform');
INSERT INTO SKILL (skill_name) VALUES ('Jenkins');
INSERT INTO SKILL (skill_name) VALUES ('Ansible');
INSERT INTO SKILL (skill_name) VALUES ('AWS');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Web Service');
INSERT INTO SKILL (skill_name) VALUES ('GCP');
INSERT INTO SKILL (skill_name) VALUES ('Google Cloud');
INSERT INTO SKILL (skill_name) VALUES ('Google Cloud Platform');
INSERT INTO SKILL (skill_name) VALUES ('Azure');
INSERT INTO SKILL (skill_name) VALUES ('Snowflake');
INSERT INTO SKILL (skill_name) VALUES ('Heroku');
INSERT INTO SKILL (skill_name) VALUES ('Salesforce Cloud');
INSERT INTO SKILL (skill_name) VALUES ('Pivotal Cloud Foundry');
INSERT INTO SKILL (skill_name) VALUES ('PCF');
INSERT INTO SKILL (skill_name) VALUES ('Tanzu');
INSERT INTO SKILL (skill_name) VALUES ('IBM Cloud');
INSERT INTO SKILL (skill_name) VALUES ('SAP Cloud');
INSERT INTO SKILL (skill_name) VALUES ('SAP Cloud Platform');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Computing');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Storage');
INSERT INTO SKILL (skill_name) VALUES ('Serverless Computing');
INSERT INTO SKILL (skill_name) VALUES ('Amazon API Gateway');
INSERT INTO SKILL (skill_name) VALUES ('Amazon RDS');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Aurora');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Lambda');
INSERT INTO SKILL (skill_name) VALUES ('Amazon EC2');
INSERT INTO SKILL (skill_name) VALUES ('Amazon VPC');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Route 53');
INSERT INTO SKILL (skill_name) VALUES ('Amazon S3');
INSERT INTO SKILL (skill_name) VALUES ('Amazon CloudFront');
INSERT INTO SKILL (skill_name) VALUES ('Amazon IAM');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Cognito');
INSERT INTO SKILL (skill_name) VALUES ('Amazon SNS');
INSERT INTO SKILL (skill_name) VALUES ('Amazon SQS');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Redshift');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Kinesis');
INSERT INTO SKILL (skill_name) VALUES ('Amazon Elastic Search');
INSERT INTO SKILL (skill_name) VALUES ('Google Cloud App Engine');
INSERT INTO SKILL (skill_name) VALUES ('gcloud CLI');
INSERT INTO SKILL (skill_name) VALUES ('Google Cloud SDK');
INSERT INTO SKILL (skill_name) VALUES ('GKE');
INSERT INTO SKILL (skill_name) VALUES ('Google Kubernetes Engine');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Pub/Sub');
INSERT INTO SKILL (skill_name) VALUES ('Stackdriver');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Run');
INSERT INTO SKILL (skill_name) VALUES ('Anthos');
INSERT INTO SKILL (skill_name) VALUES ('Bigtable');
INSERT INTO SKILL (skill_name) VALUES ('Firestore');
INSERT INTO SKILL (skill_name) VALUES ('Memorystore');
INSERT INTO SKILL (skill_name) VALUES ('Spanner');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Dataflow');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Dataproc');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Dataprep');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Datalab');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Source Repositories');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Scheduler');
INSERT INTO SKILL (skill_name) VALUES ('Container Registry');
INSERT INTO SKILL (skill_name) VALUES ('Apache Beam');
INSERT INTO SKILL (skill_name) VALUES ('Istio');
INSERT INTO SKILL (skill_name) VALUES ('Azure Cognitive Services');
INSERT INTO SKILL (skill_name) VALUES ('Azure Compute');
INSERT INTO SKILL (skill_name) VALUES ('Azure Functions');
INSERT INTO SKILL (skill_name) VALUES ('Azure Blob storage');
INSERT INTO SKILL (skill_name) VALUES ('Azure cFile storage');
INSERT INTO SKILL (skill_name) VALUES ('Azure Active Directory');
INSERT INTO SKILL (skill_name) VALUES ('Azure Key Vault');
INSERT INTO SKILL (skill_name) VALUES ('Azure Analytics');
INSERT INTO SKILL (skill_name) VALUES ('Azure AI');
INSERT INTO SKILL (skill_name) VALUES ('Azure Kubernetes Service');
INSERT INTO SKILL (skill_name) VALUES ('Azure Container Registry');
INSERT INTO SKILL (skill_name) VALUES ('Azure DevOps');
INSERT INTO SKILL (skill_name) VALUES ('Azure Pipelines');
INSERT INTO SKILL (skill_name) VALUES ('Azure Repos');
INSERT INTO SKILL (skill_name) VALUES ('Azure Test Plans');
INSERT INTO SKILL (skill_name) VALUES ('Public Cloud');
INSERT INTO SKILL (skill_name) VALUES ('Private Cloud');
INSERT INTO SKILL (skill_name) VALUES ('Hybrid Cloud');
INSERT INTO SKILL (skill_name) VALUES ('AI');
INSERT INTO SKILL (skill_name) VALUES ('Machine Learning');
INSERT INTO SKILL (skill_name) VALUES ('TensorFlow');
INSERT INTO SKILL (skill_name) VALUES ('IoT');
INSERT INTO SKILL (skill_name) VALUES ('Internet of things');
INSERT INTO SKILL (skill_name) VALUES ('Jupyter Notebook');
INSERT INTO SKILL (skill_name) VALUES ('SQL');
INSERT INTO SKILL (skill_name) VALUES ('PLSQL');
INSERT INTO SKILL (skill_name) VALUES ('TSQL');
INSERT INTO SKILL (skill_name) VALUES ('NoSQL');
INSERT INTO SKILL (skill_name) VALUES ('DynamoDB');
INSERT INTO SKILL (skill_name) VALUES ('Big Query');
INSERT INTO SKILL (skill_name) VALUES ('Cosmos DB');
INSERT INTO SKILL (skill_name) VALUES ('MongoDB');
INSERT INTO SKILL (skill_name) VALUES ('RDBMS');
INSERT INTO SKILL (skill_name) VALUES ('MySQL');
INSERT INTO SKILL (skill_name) VALUES ('PostgreSQL');
INSERT INTO SKILL (skill_name) VALUES ('Oracle');
INSERT INTO SKILL (skill_name) VALUES ('MS SQL Server');
INSERT INTO SKILL (skill_name) VALUES ('DB2');
INSERT INTO SKILL (skill_name) VALUES ('OpenShift');
INSERT INTO SKILL (skill_name) VALUES ('Cloud Foundry');
INSERT INTO SKILL (skill_name) VALUES ('PaaS');
INSERT INTO SKILL (skill_name) VALUES ('IaaS');
INSERT INTO SKILL (skill_name) VALUES ('SaaS');
INSERT INTO SKILL (skill_name) VALUES ('REST');
INSERT INTO SKILL (skill_name) VALUES ('GraphQL');
INSERT INTO SKILL (skill_name) VALUES ('gRPC');
INSERT INTO SKILL (skill_name) VALUES ('SOAP');
INSERT INTO SKILL (skill_name) VALUES ('SOA');
INSERT INTO SKILL (skill_name) VALUES ('Web Services');
INSERT INTO SKILL (skill_name) VALUES ('Spring Boot');
INSERT INTO SKILL (skill_name) VALUES ('Spring');
INSERT INTO SKILL (skill_name) VALUES ('DI');
INSERT INTO SKILL (skill_name) VALUES ('Dependency Injection');
INSERT INTO SKILL (skill_name) VALUES ('IoC');
INSERT INTO SKILL (skill_name) VALUES ('Inversion of Control');
INSERT INTO SKILL (skill_name) VALUES ('AOP');
INSERT INTO SKILL (skill_name) VALUES ('Autowired');
INSERT INTO SKILL (skill_name) VALUES ('Spring MVC');
INSERT INTO SKILL (skill_name) VALUES ('Spring Data');
INSERT INTO SKILL (skill_name) VALUES ('Django');
INSERT INTO SKILL (skill_name) VALUES ('Django REST');
INSERT INTO SKILL (skill_name) VALUES ('Kafka');
INSERT INTO SKILL (skill_name) VALUES ('RabbitMQ');
INSERT INTO SKILL (skill_name) VALUES ('Redis');
INSERT INTO SKILL (skill_name) VALUES ('JMS');
INSERT INTO SKILL (skill_name) VALUES ('Git');
INSERT INTO SKILL (skill_name) VALUES ('GitHub');
INSERT INTO SKILL (skill_name) VALUES ('GitLab');
INSERT INTO SKILL (skill_name) VALUES ('YAML');
INSERT INTO SKILL (skill_name) VALUES ('JSON');
INSERT INTO SKILL (skill_name) VALUES ('XML');
INSERT INTO SKILL (skill_name) VALUES ('Shopify');
INSERT INTO SKILL (skill_name) VALUES ('SPA');
INSERT INTO SKILL (skill_name) VALUES ('Expo');
INSERT INTO SKILL (skill_name) VALUES ('Apple');
INSERT INTO SKILL (skill_name) VALUES ('Andriod');
INSERT INTO SKILL (skill_name) VALUES ('IBM InfoSphere');
INSERT INTO SKILL (skill_name) VALUES ('IBM WebSphere');
INSERT INTO SKILL (skill_name) VALUES ('IBM DataStage and QualityStage');
INSERT INTO SKILL (skill_name) VALUES ('IBM Cognos');
INSERT INTO SKILL (skill_name) VALUES ('Informatica PowerCenter');
INSERT INTO SKILL (skill_name) VALUES ('Informatica Developer');
INSERT INTO SKILL (skill_name) VALUES ('Big Data');
INSERT INTO SKILL (skill_name) VALUES ('ETL');
INSERT INTO SKILL (skill_name) VALUES ('Data Integration');
INSERT INTO SKILL (skill_name) VALUES ('Data Quality');
INSERT INTO SKILL (skill_name) VALUES ('Data Warehouse');
INSERT INTO SKILL (skill_name) VALUES ('Data Analytics');
INSERT INTO SKILL (skill_name) VALUES ('Data Ingestion');
INSERT INTO SKILL (skill_name) VALUES ('Data Governance');
INSERT INTO SKILL (skill_name) VALUES ('Data Migration');
INSERT INTO SKILL (skill_name) VALUES ('Data Visualization');
INSERT INTO SKILL (skill_name) VALUES ('MDM');
INSERT INTO SKILL (skill_name) VALUES ('Master Data Management');
INSERT INTO SKILL (skill_name) VALUES ('Data Lake');
INSERT INTO SKILL (skill_name) VALUES ('SSIS');
INSERT INTO SKILL (skill_name) VALUES ('SSAS');
INSERT INTO SKILL (skill_name) VALUES ('oAuth');
INSERT INTO SKILL (skill_name) VALUES ('OIDC');
INSERT INTO SKILL (skill_name) VALUES ('OpenID Connect');
INSERT INTO SKILL (skill_name) VALUES ('JWT');
INSERT INTO SKILL (skill_name) VALUES ('JSON Web Token');
INSERT INTO SKILL (skill_name) VALUES ('SAML');
INSERT INTO SKILL (skill_name) VALUES ('OAS');
INSERT INTO SKILL (skill_name) VALUES ('Swagger');
INSERT INTO SKILL (skill_name) VALUES ('TDD');
INSERT INTO SKILL (skill_name) VALUES ('BDD');
INSERT INTO SKILL (skill_name) VALUES ('Mock');
INSERT INTO SKILL (skill_name) VALUES ('WireMock');
INSERT INTO SKILL (skill_name) VALUES ('SOLID');
INSERT INTO SKILL (skill_name) VALUES ('TLS');
INSERT INTO SKILL (skill_name) VALUES ('SSL');
INSERT INTO SKILL (skill_name) VALUES ('TCP/IP');
INSERT INTO SKILL (skill_name) VALUES ('HTTP');
INSERT INTO SKILL (skill_name) VALUES ('Unix');
INSERT INTO SKILL (skill_name) VALUES ('Linux');
INSERT INTO SKILL (skill_name) VALUES ('Windows');
INSERT INTO SKILL (skill_name) VALUES ('Bourne shell (sh)');
INSERT INTO SKILL (skill_name) VALUES ('Korn shell (ksh)');
INSERT INTO SKILL (skill_name) VALUES ('Bourne Again shell (bash)');
INSERT INTO SKILL (skill_name) VALUES ('POSIX shell (sh)');
INSERT INTO SKILL (skill_name) VALUES ('C Shell (csh)');
INSERT INTO SKILL (skill_name) VALUES ('TENEX/TOPS C shell (tcsh)');
INSERT INTO SKILL (skill_name) VALUES ('Ubuntu');
INSERT INTO SKILL (skill_name) VALUES ('Debian');
INSERT INTO SKILL (skill_name) VALUES ('Centos');
INSERT INTO SKILL (skill_name) VALUES ('AODA');
INSERT INTO SKILL (skill_name) VALUES ('WCAG');
INSERT INTO SKILL (skill_name) VALUES ('Screen reader');
INSERT INTO SKILL (skill_name) VALUES ('HiSoftware Compliance Sheriff');
INSERT INTO SKILL (skill_name) VALUES ('WAVE toolbar');
INSERT INTO SKILL (skill_name) VALUES ('Colour Contrast Check');
INSERT INTO SKILL (skill_name) VALUES ('JIRA');
INSERT INTO SKILL (skill_name) VALUES ('Confluence');
INSERT INTO SKILL (skill_name) VALUES ('WebLogic');
INSERT INTO SKILL (skill_name) VALUES ('Oracle WebLogic');
INSERT INTO SKILL (skill_name) VALUES ('RedHat WildFly');
INSERT INTO SKILL (skill_name) VALUES ('RedHat JBoss');
INSERT INTO SKILL (skill_name) VALUES ('Tomcat');
INSERT INTO SKILL (skill_name) VALUES ('QC');
INSERT INTO SKILL (skill_name) VALUES ('HP QC');
INSERT INTO SKILL (skill_name) VALUES ('Quality Center');
INSERT INTO SKILL (skill_name) VALUES ('ALM');
INSERT INTO SKILL (skill_name) VALUES ('HP ALM');
INSERT INTO SKILL (skill_name) VALUES ('Application Lifecycle Management');
INSERT INTO SKILL (skill_name) VALUES ('JDBC');
INSERT INTO SKILL (skill_name) VALUES ('ODBC');
INSERT INTO SKILL (skill_name) VALUES ('PowerShell');
INSERT INTO SKILL (skill_name) VALUES ('DOS');
INSERT INTO SKILL (skill_name) VALUES ('C');
INSERT INTO SKILL (skill_name) VALUES ('C++');
INSERT INTO SKILL (skill_name) VALUES ('Visual Basic .Net');
INSERT INTO SKILL (skill_name) VALUES ('EJB');
INSERT INTO SKILL (skill_name) VALUES ('JSP');
INSERT INTO SKILL (skill_name) VALUES ('Servlet');
INSERT INTO SKILL (skill_name) VALUES ('Struts');
INSERT INTO SKILL (skill_name) VALUES ('Apache Struts 2');
INSERT INTO SKILL (skill_name) VALUES ('Hibernate');
INSERT INTO SKILL (skill_name) VALUES ('JUnit');
INSERT INTO SKILL (skill_name) VALUES ('SVN');
INSERT INTO SKILL (skill_name) VALUES ('ASP');
INSERT INTO SKILL (skill_name) VALUES ('CGI');
INSERT INTO SKILL (skill_name) VALUES ('Perl');
INSERT INTO SKILL (skill_name) VALUES ('Basic');
INSERT INTO SKILL (skill_name) VALUES ('Fortran');
INSERT INTO SKILL (skill_name) VALUES ('Pascal');
INSERT INTO SKILL (skill_name) VALUES ('Delphi');
INSERT INTO SKILL (skill_name) VALUES ('COBOL');
INSERT INTO SKILL (skill_name) VALUES ('J#');
INSERT INTO SKILL (skill_name) VALUES ('F#');
INSERT INTO SKILL (skill_name) VALUES ('DHTML');
INSERT INTO SKILL (skill_name) VALUES ('Borland C++');
INSERT INTO SKILL (skill_name) VALUES ('ActionScript');
INSERT INTO SKILL (skill_name) VALUES ('DBA');
INSERT INTO SKILL (skill_name) VALUES ('System Admin');
INSERT INTO SKILL (skill_name) VALUES ('Unix Admin');
INSERT INTO SKILL (skill_name) VALUES ('AIX');
INSERT INTO SKILL (skill_name) VALUES ('Solaris');

