/**
 * calculates the subtotal, taxes, and grand total to buy items from Emily's eClips
 *
 * modified 20210813
 * date 20210813
 * @filename ClipPurchaseCalculator.java
 * @author Emily Su
 * @version 1.0
 */
// note: "HClips" stands for hair clips
// note: "PClips" stands for paper clips
public class ClipPurchaseCalculator extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L; // https://stackoverflow.com/questions/2288937/what-does-it-mean-the-serializable-class-does-not-declare-a-static-final-serial

    /**
     * Creates new form FrmClipsForm
     */
    public ClipPurchaseCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblInstructions_1 = new javax.swing.JLabel();
        lblInstructions_2 = new javax.swing.JLabel();
        lblPaperClips = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblGreyPClips = new javax.swing.JLabel();
        lblPinkPClips = new javax.swing.JLabel();
        lblPurplePClips = new javax.swing.JLabel();
        lblQuantity_6 = new javax.swing.JLabel();
        lblQuantity_4 = new javax.swing.JLabel();
        lblQuantity_5 = new javax.swing.JLabel();
        txtGreyPClips = new javax.swing.JTextField();
        txtPurplePClips = new javax.swing.JTextField();
        txtPinkPClips = new javax.swing.JTextField();
        lblPinkPClipsImage = new javax.swing.JLabel();
        lblGreyPClipsImage = new javax.swing.JLabel();
        lblPurplePClipsImage = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblPinkHClips = new javax.swing.JLabel();
        lblPurpleHClips = new javax.swing.JLabel();
        lblBlackHClips = new javax.swing.JLabel();
        lblQuantity_2 = new javax.swing.JLabel();
        lblQuantity_3 = new javax.swing.JLabel();
        lblQuantity_1 = new javax.swing.JLabel();
        txtPurpleHClips = new javax.swing.JTextField();
        txtBlackHClips = new javax.swing.JTextField();
        txtPinkHClips = new javax.swing.JTextField();
        lblBlackHClipsImage = new javax.swing.JLabel();
        lblPinkHClipsImage = new javax.swing.JLabel();
        lblPurpleHClipsImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        lblnstructions_4 = new javax.swing.JLabel();
        lblInstructions_3 = new javax.swing.JLabel();
        lblResultStatus = new javax.swing.JLabel();
        lblSubtitleTaxes = new javax.swing.JLabel();
        lblSubtitleGrandTotal = new javax.swing.JLabel();
        lblSubtitleStatus = new javax.swing.JLabel();
        lblSubtitleSubtotal = new javax.swing.JLabel();
        lblValueGrandTotal = new javax.swing.JLabel();
        lblValueSubtotal = new javax.swing.JLabel();
        lblValueTaxes = new javax.swing.JLabel();
        lblHairClips = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setToolTipText("");

        lblTitle.setFont(new java.awt.Font("Bangla MN", 0, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Emily's eClips!");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblInstructions_1.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblInstructions_1.setText("Calculate your purchases of clips electronically from Emily's eClips!");

        lblInstructions_2.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblInstructions_2.setText("Enter the number of each product that you would like to buy:");

        lblPaperClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblPaperClips.setText("Paper Clips:");

        jPanel6.setBackground(new java.awt.Color(255, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblGreyPClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblGreyPClips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreyPClips.setText("Grey Paper Clips! ($3.99)");

        lblPinkPClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblPinkPClips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPinkPClips.setText("Pink Paper Clips! ($4.99)");

        lblPurplePClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblPurplePClips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPurplePClips.setText("Purple Paper Clips! ($4.99)");

        lblQuantity_6.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblQuantity_6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity_6.setText("Quantity:");

        lblQuantity_4.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblQuantity_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity_4.setText("Quantity:");

        lblQuantity_5.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblQuantity_5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity_5.setText("Quantity:");

        txtGreyPClips.setText("0");
        txtGreyPClips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGreyPClipsActionPerformed(evt);
            }
        });

        txtPurplePClips.setText("0");
        txtPurplePClips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurplePClipsActionPerformed(evt);
            }
        });

        txtPinkPClips.setText("0");
        txtPinkPClips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinkPClipsActionPerformed(evt);
            }
        });

        lblPinkPClipsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("./pinkpaperclips.jpeg"))); // https://www.bcicrafts.com/Jumbo-Metal-Paper-Clips-4-Pink-12-pc_p_2186.html

        lblGreyPClipsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("./greypaperclips.jpeg"))); // https://wyqixiang.en.made-in-china.com/product/OKexjqTMlChJ/China-Nickel-Plated-Boat-Shaped-Paper-Clip-QX-PC007-43-50mm.html

        lblPurplePClipsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("./purplepaperclips.jpeg"))); // https://www.bcicrafts.com/Jumbo-Metal-Paper-Clips-4-Purple-12-pc_p_2187.html

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGreyPClips, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblGreyPClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblPurplePClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPurplePClips, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPinkPClips, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblPinkPClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblQuantity_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtGreyPClips, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblQuantity_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtPurplePClips, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblQuantity_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtPinkPClips, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPinkPClips)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGreyPClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPurplePClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPinkPClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblGreyPClips, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPurplePClips, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantity_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGreyPClips, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurplePClips, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPinkPClips, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBackground(new java.awt.Color(255, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPinkHClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblPinkHClips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPinkHClips.setText("Pink Hair Clips! ($10.99)");

        lblPurpleHClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblPurpleHClips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPurpleHClips.setText("Purple Hair Clips! ($7.99)");

        lblBlackHClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblBlackHClips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlackHClips.setText("Black Hair Clips! ($5.99)");

        lblQuantity_2.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblQuantity_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity_2.setText("Quantity:");

        lblQuantity_3.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblQuantity_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity_3.setText("Quantity:");

        lblQuantity_1.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblQuantity_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuantity_1.setText("Quantity:");

        txtPurpleHClips.setText("0");
        txtPurpleHClips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurpleHClipsActionPerformed(evt);
            }
        });

        txtBlackHClips.setText("0");
        txtBlackHClips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlackHClipsActionPerformed(evt);
            }
        });

        txtPinkHClips.setText("0");
        txtPinkHClips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinkHClipsActionPerformed(evt);
            }
        });

        lblBlackHClipsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("./blackhairclips.png"))); // https://www.amazon.ca/Just-Basic-Black-Metal-Clips/dp/B008S5743A

        lblPinkHClipsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("./pinkhairclips.jpg"))); // https://www.etsy.com/market/pink_hair_clip

        lblPurpleHClipsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("./purplehairclips.jpeg"))); // https://www.monkhouse.com/p/4768/Unicol-Click-Clack-Purple-Hair-Clips

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblBlackHClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBlackHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblPurpleHClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPurpleHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPinkHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblPinkHClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblQuantity_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtBlackHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblQuantity_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtPurpleHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblQuantity_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtPinkHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBlackHClips)
                    .addComponent(lblPurpleHClips)
                    .addComponent(lblPinkHClips)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlackHClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPurpleHClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPinkHClipsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantity_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlackHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPurpleHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPinkHClips, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCalculate.setFont(new java.awt.Font("Bangla MN", 1, 18)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(204, 0, 51));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblnstructions_4.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblnstructions_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnstructions_4.setText("calculate your order!");

        lblInstructions_3.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblInstructions_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions_3.setText("Click this button to ");

        lblResultStatus.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblResultStatus.setText("You have not calculated yet.");

        lblSubtitleTaxes.setFont(new java.awt.Font("Bangla MN", 0, 16)); // NOI18N
        lblSubtitleTaxes.setText("Taxes ($):");

        lblSubtitleGrandTotal.setFont(new java.awt.Font("Bangla MN", 0, 16)); // NOI18N
        lblSubtitleGrandTotal.setText("Grand Total ($):");

        lblSubtitleStatus.setFont(new java.awt.Font("Bangla MN", 0, 16)); // NOI18N
        lblSubtitleStatus.setText("Status of Calculation:");

        lblSubtitleSubtotal.setFont(new java.awt.Font("Bangla MN", 0, 16)); // NOI18N
        lblSubtitleSubtotal.setText("Subtotal ($):");

        lblValueGrandTotal.setFont(new java.awt.Font("Bangla MN", 0, 16)); // NOI18N
        lblValueGrandTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueGrandTotal.setText("0.00");

        lblValueSubtotal.setFont(new java.awt.Font("Bangla MN", 0, 16)); // NOI18N
        lblValueSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueSubtotal.setText("0.00");

        lblValueTaxes.setFont(new java.awt.Font("Bangla MN", 0, 16)); // NOI18N
        lblValueTaxes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueTaxes.setText("0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblInstructions_3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblnstructions_4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSubtitleSubtotal)
                        .addGap(41, 41, 41)
                        .addComponent(lblValueSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSubtitleTaxes)
                        .addGap(65, 65, 65)
                        .addComponent(lblValueTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSubtitleGrandTotal)
                        .addGap(12, 12, 12)
                        .addComponent(lblValueGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSubtitleStatus))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblResultStatus)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstructions_3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblnstructions_4)))
                .addGap(12, 12, 12)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitleSubtotal)
                    .addComponent(lblValueSubtotal))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitleTaxes)
                    .addComponent(lblValueTaxes))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitleGrandTotal)
                    .addComponent(lblValueGrandTotal))
                .addGap(50, 50, 50)
                .addComponent(lblSubtitleStatus)
                .addGap(6, 6, 6)
                .addComponent(lblResultStatus))
        );

        lblHairClips.setFont(new java.awt.Font("Bangla MN", 0, 13)); // NOI18N
        lblHairClips.setText("Hair Clips:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstructions_2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInstructions_1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHairClips, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPaperClips, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblInstructions_2))
                            .addComponent(lblInstructions_1))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHairClips))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPaperClips)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        int blackHClips;
        int purpleHClips;
        int pinkHClips;
        int greyPClips;
        int purplePClips;
        int pinkPClips;
        final double BLACK_H_CLIPS_PRICE = 5.99;
        final double PURPLE_H_CLIPS_PRICE = 7.99;
        final double PINK_H_CLIPS_PRICE = 10.99;
        final double GREY_P_CLIPS_PRICE = 3.99;
        final double PURPLE_P_CLIPS_PRICE = 4.99;
        final double PINK_P_CLIPS_PRICE = 4.99;
        final double TAX_RATE = 0.13;
        double subtotal;
        double taxes;
        double grandTotal;
        double subtotalRounded;
        double taxesRounded;
        double grandTotalRounded;

        blackHClips = Integer.parseInt(txtBlackHClips.getText());
        purpleHClips = Integer.parseInt(txtPurpleHClips.getText());
        pinkHClips = Integer.parseInt(txtPinkHClips.getText());
        greyPClips = Integer.parseInt(txtGreyPClips.getText());
        purplePClips = Integer.parseInt(txtPurplePClips.getText());
        pinkPClips = Integer.parseInt(txtPinkPClips.getText());

        subtotal = blackHClips * BLACK_H_CLIPS_PRICE + purpleHClips * PURPLE_H_CLIPS_PRICE
                + pinkHClips * PINK_H_CLIPS_PRICE + greyPClips * GREY_P_CLIPS_PRICE
                + purplePClips * PURPLE_P_CLIPS_PRICE + pinkPClips * PINK_P_CLIPS_PRICE;
        taxes = subtotal * TAX_RATE;
        grandTotal = subtotal + taxes;

        // rounding
        subtotalRounded = Math.round(subtotal * 100.0) / 100.0; // https://www.delftstack.com/howto/java/how-to-round-a-double-to-two-decimal-places-in-java/
        taxesRounded = Math.round(taxes * 100.0) / 100.0; // https://www.delftstack.com/howto/java/how-to-round-a-double-to-two-decimal-places-in-java/
        grandTotalRounded = Math.round(grandTotal * 100.0) / 100.0; // https://www.delftstack.com/howto/java/how-to-round-a-double-to-two-decimal-places-in-java/

        if (blackHClips < 0 || purpleHClips < 0 || pinkHClips < 0 || greyPClips < 0 || purplePClips < 0
                || pinkPClips < 0) {
            lblResultStatus.setText("Error. Do not use negative values!");
        } else {
            lblValueSubtotal.setText(String.valueOf(subtotalRounded));
            lblValueTaxes.setText(String.valueOf(taxesRounded));
            lblValueGrandTotal.setText(String.valueOf(grandTotalRounded));
            lblResultStatus.setText("Completed!");
        }

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtPinkHClipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinkHClipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinkHClipsActionPerformed

    private void txtPurpleHClipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurpleHClipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurpleHClipsActionPerformed

    private void txtBlackHClipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlackHClipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlackHClipsActionPerformed

    private void txtGreyPClipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGreyPClipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGreyPClipsActionPerformed

    private void txtPurplePClipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurplePClipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurplePClipsActionPerformed

    private void txtPinkPClipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinkPClipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinkPClipsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClipPurchaseCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClipPurchaseCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClipPurchaseCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClipPurchaseCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClipPurchaseCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblBlackHClips;
    private javax.swing.JLabel lblBlackHClipsImage;
    private javax.swing.JLabel lblGreyPClips;
    private javax.swing.JLabel lblGreyPClipsImage;
    private javax.swing.JLabel lblHairClips;
    private javax.swing.JLabel lblInstructions_1;
    private javax.swing.JLabel lblInstructions_2;
    private javax.swing.JLabel lblInstructions_3;
    private javax.swing.JLabel lblPaperClips;
    private javax.swing.JLabel lblPinkHClips;
    private javax.swing.JLabel lblPinkHClipsImage;
    private javax.swing.JLabel lblPinkPClips;
    private javax.swing.JLabel lblPinkPClipsImage;
    private javax.swing.JLabel lblPurpleHClips;
    private javax.swing.JLabel lblPurpleHClipsImage;
    private javax.swing.JLabel lblPurplePClips;
    private javax.swing.JLabel lblPurplePClipsImage;
    private javax.swing.JLabel lblQuantity_1;
    private javax.swing.JLabel lblQuantity_2;
    private javax.swing.JLabel lblQuantity_3;
    private javax.swing.JLabel lblQuantity_4;
    private javax.swing.JLabel lblQuantity_5;
    private javax.swing.JLabel lblQuantity_6;
    private javax.swing.JLabel lblResultStatus;
    private javax.swing.JLabel lblSubtitleGrandTotal;
    private javax.swing.JLabel lblSubtitleStatus;
    private javax.swing.JLabel lblSubtitleSubtotal;
    private javax.swing.JLabel lblSubtitleTaxes;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValueGrandTotal;
    private javax.swing.JLabel lblValueSubtotal;
    private javax.swing.JLabel lblValueTaxes;
    private javax.swing.JLabel lblnstructions_4;
    private javax.swing.JTextField txtBlackHClips;
    private javax.swing.JTextField txtGreyPClips;
    private javax.swing.JTextField txtPinkHClips;
    private javax.swing.JTextField txtPinkPClips;
    private javax.swing.JTextField txtPurpleHClips;
    private javax.swing.JTextField txtPurplePClips;
    // End of variables declaration//GEN-END:variables
}
